name: trivia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # For checking network connectivity
  connectivity_plus: 
  # Functional programming thingies
  dartz: 
  # For making HTTP requests
  dio: 
  # For equality checks
  equatable: 
  # For Bloc state management
  flutter_bloc: 
  # For service locator pattern
  get_it: ^8.0.3
  # For mocking in tests
  # For reading/writing persistent data
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.14
  test: ^1.25.8

flutter:
  uses-material-design: true
